import 'package:get/get.dart';

class Translate extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'ar': {
          'Signin_Appbar': 'تسجيل الدخول',
          'Signin_Label1': 'تسجيل الدخول',
          'Signin_Label2': 'مرحبا بك مجددا , أدخل رقم هاتفك للدخول إلى التطبيق',
          'Signin_Label3': 'رقم الهاتف',
          'Signin_Label4':
              'بالنقر على متابعة ، فأنت توافق على شروط وسياسة المستخدم',
          'Signin_Button': 'تسجيل الدخول',
          'VerifyAccount_Appbar': 'تفعيل الحساب',
          'VerifyAccount_Label1': 'تفعيل الحساب',
          'VerifyAccount_Label2': 'لقد أرسلنا رمز إلى رقم جوالك',
          'VerifyAccount_Label3': 'يحتوي على رمز تفعيل من 6 خانات',
          'VerifyAccount_Label4': 'لم تستلم رمز ؟',
          'VerifyAccount_Label5': 'إعادة الإرسال',
          'VerifyAccount_Button': 'تفعيل',
          'More_Appbar': 'المزيد',
          'More_Label1': 'الشروط والأحكام',
          'More_Label2': 'الإعدادات',
          'More_Label3': 'تواصل معنا',
          'PrivacyAndTerms_Appbar': 'الشروط والأحكام',
          'PrivacyAndTerms_Label1': 'شروط الاستخدام',
          'PrivacyAndTerms_Label2': '',
          'MyAccount_Appbar': 'حسابي',
          'MyAccount_Label1': 'أنت مسجل معنا برقم هاتف',
          'MyAccount_Label2': 'تسجيل الخروج',
          'MyAccount_Label3': 'إعلاناتي المفضلة',
          'MyAccount_Label4': 'إعلاناتي',
          'MyAccount_Label5': 'المراسلة المباشرة مع الإدارة',
          '': '',
          '': '',
          '': '',
          'appbar': 'الإعدادات',
          'language': 'اللغة',
          'theme': 'الوضع المظلم',
        },
        'en': {
          'Signin_Appbar': 'Sign in',
          'Signin_Label1': 'Sign in',
          'Signin_Label2':
              'Welcome again , enter your phone number to enter the application',
          'Signin_Label3': 'Phone number',
          'Signin_Label4':
              'By clicking Continue, you agree to our User Terms and Policy',
          'Signin_Button': 'Sign in',
          'VerifyAccount_Appbar': 'activate the account',
          'VerifyAccount_Label1': 'activate the account',
          'VerifyAccount_Label2': 'We have sent a code to your mobile number',
          'VerifyAccount_Label3': 'Contains a 6-digit activation code',
          'VerifyAccount_Label4': 'Didn\'t receive a code ?',
          'VerifyAccount_Label5': 'Re-transmitter',
          'VerifyAccount_Button': 'activation',
          'More_Appbar': 'More',
          'More_Label1': 'Privacy and terms',
          'More_Label2': 'Settings',
          'More_Label3': 'Connect with us',
          'PrivacyAndTerms_Appbar': 'Privacy and terms',
          'PrivacyAndTerms_Label1': 'Terms of use',
          'PrivacyAndTerms_Label2': '',
          'MyAccount_Appbar': 'My account',
          'MyAccount_Label1': 'You are registered with us with a phone number',
          'MyAccount_Label2': 'Sign out',
          'MyAccount_Label3': 'My favorite ads',
          'MyAccount_Label4': 'My ads',
          'MyAccount_Label5': 'Direct correspondence with management',
          '': '',
          '': '',
          '': '',
          '': '',
          '': '',
          'appbar': 'Setting',
          'language': 'Language',
          'theme': 'Dark Mode',
        },
      };
}
